import { PersonStanding, House, Package, Heart, type LucideIcon } from 'lucide-react';

export interface ThemeConfig {
    label: string;
    color: string;
    icon: LucideIcon;
    description: string;
}

export const THEME_CONFIG: Record<string, ThemeConfig> = {
    corpi: {
        label: 'Corpi',
        color: '#eab308',
        icon: PersonStanding,
        description: `Un percorso per i corpi, perché sono la traccia più concreta di quello che è successo. Il corpo è un simbolo di identità e proprio per questo, quando si fa del male fisico a una persona, si ferisce anche la sua anima. Per far scomparire una persona dalla faccia della terra, come volevano i nazifascisti, la prima cosa da fare è liberarsi del corpo.\n\nA partire dai corpi si capisce chi è in fuga e chi insegue, chi usa violenza e chi la subisce. Ma i corpi che incontriamo in questi documenti non raccontano solo le offese e ingiustizie: raccontano anche la vita quotidiana, la cura, la ricerca di salvezza. Sono corpi che si muovono per la città, che cercano un lavoro, che abitano case, che attraversano confini, che tornano indietro stanchi, che chiedono cibo, riposo, medicine, che cercano di restare vivi e di tenere vive le relazioni. Le pietre d’inciampo ricordano anche questo: corpi di persone grandi e piccole, maschi e femmine, persone anziane strappate alla quotidianità, ma ancora leggibili nelle tracce che hanno lasciato.\n\nPrendersi cura del corpo di un’altra persona è un gesto concreto che inverte la logica della violenza. Non basta eliminare un corpo per far sparire una persona: ne resta sempre qualche traccia, e resta il ricordo. È anche questo che gli itinerari vogliono mostrare.`,
    },
    case: {
        label: 'Casa',
        color: '#16a34a',
        icon: House,
        description: `Un percorso per le case, perché sono una traccia molto concreta della vita delle persone. La casa è il luogo in cui si passa la maggior parte del tempo, in cui ci si sente al sicuro e si può essere sé stesse e sé stessi. È il luogo dei legami, delle relazioni familiari e amicali, anche per le persone di cui stiamo raccontando la storia. Per molte donne di questo percorso, e non solo, era anche il luogo in cui il regime fascista le voleva: chiamate a fare figli per la patria e costrette a restare dentro lo spazio domestico. Abbiamo anche visto come per le donne operaie la fabbrica potesse invece diventare un luogo di relazioni, di affetti, di vita condivisa e di consapevolezza politica.\n\nGuardando i documenti ci siamo accorte e accorti che la storia si può leggere anche dalle case. La casa è l’ultimo luogo di vita libera, ma è anche il luogo segnato nei censimenti, negli elenchi, nelle carte di polizia. Può diventare una trappola per chi è braccata o braccato, ebrea o ebreo, perseguitata o perseguitato politico. È la casa che si lascia per tentare di fuggire in Svizzera, quella in cui non si dorme nei giorni delle grandi retate, quella in cui restano le cose a cui si era affezionate.\n\nLa casa è il luogo degli affetti e degli oggetti. È ciò che si porta con sè nel pensiero e nella speranza di un ritorno o nella paura, a volte nella certezza, di una separazione definitiva. Ma è anche un orizzonte da raccontare e a cui si desidera tornare nei ricordi, nei racconti nelle strade della città dove quelle vite hanno lasciato tracce.`,
    },
    cose: {
        label: 'Cose',
        color: '#2563eb',
        icon: Package,
        description: `Un percorso per le cose, testimonianze vive, dirette e concrete, perché anche gli oggetti sono una traccia, e li abbiamo seguiti per raccontare delle vite. Gli oggetti sono testimoni, testimoni silenti che la nostra curiosità e attenzione fa parlare.\n\nGli inventari aiutano a capire com’era la vita delle persone prima del carcere o del campo. Mostrano quali oggetti venivano usati più spesso, a che cosa servivano e chi li usava; a volte, fanno intravedere anche se una famiglia viveva con molto oppure con poco. Ci portano nella concretezza della vita vissuta.\n\nQuando quelle vite vengono spezzate, anche le cose cambiano significato. Nelle lettere che partono dal carcere si chiedono vestiti, sapone, cibo, piccoli oggetti per sentirsi un poco più pulite e puliti, per rimettersi in ordine, per affrontare le giornate. Sono richieste che raccontano quanto mancassero le cose più elementari, ma anche il tentativo di conservare abitudini, dignità, legami con il mondo di fuori.\n\nE viceversa. Occuparsi di chi non ha più la libertà è un moto umano di vicinanza e amore.\n\nLe molte lettere scritte quando il compagno è in prigione mostrano la cura con cui queste donne cercavano di star loro accanto: chiedono di cosa abbia bisogno, provano a capire che cosa possa farlo stare meglio, come rendere meno duro il tempo della detenzione, anche quando le risorse sono pochissime. Anche gli elenchi delle cose sequestrate dopo gli arresti o le fughe precipitose, raccontano molto: ricordano tutto ciò che passava dalle case, dalle mani, dalle stanze di queste persone. Le cose mandate, cercate, custodite o perdute continuando così a parlare di cura, tentativi di restare in relazione, piccoli gesti che tengono insieme vite separate.`,
    },
    amore: {
        label: 'Amore',
        color: '#ef4444',
        icon: Heart,
        description: `Un itinerario per l’amore, perché l’amore attraversa i documenti e raggiunge anche noi, dentro questo percorso. Assenza, cura, passione, nostalgia, struggimento, amore materno, filiale e coniugale, ma anche la solidarietà di vicini di casa e di persone capaci di gentilezza: erano tra le forze che davano speranza e permettevano di andare avanti. Ripensare alle persone care e a quelle amate aiutava a superare i momenti più bui.\n\nNon è un caso che questo sia l’itinerario che passa per più pietre d’inciampo.\n\nNei documenti letti queste forme d’amore compaiono nei biglietti, nei diari, nelle lettere, nelle parole scambiate tra le case e il carcere, tra le città e i confini. Ci hanno colpito soprattutto i gesti più semplici: madri che pregavano per vedere i propri figli e figlie, mogli che cercavano notizie dei mariti detenuti, figlie che scrivevano piene di nostalgia alle madri e ai familiari. La preoccupazione per le persone care, il bisogno di dire ancora il proprio amore, forse anche la paura di perdere chi si ama, ricorrono in molti dei documenti che abbiamo letto.\n\nAttraverso queste parole, le pietre d’inciampo fanno sentire le tante voci della città di allora. Non restano nomi lontani, ma persone che hanno abitato strade, case, giardini pubblici. In questo modo il percorso dell’amore ridà alla città presenze e rapporti spezzati dalla violenza della guerra. Guardare la storia attraverso l’amore ci ha aiutato ad allargare lo sguardo: le persone che abbiamo raccontato non appaiono più da sole, ma insieme ad altri e altre, dentro corpi, affetti e idee condivise. Così non vediamo più figure isolate, ma donne e uomini dentro i momenti e gesti delle loro vite.`,
    },
};
